model:
  model_dir: models/outfile_14_best.pt
  data_dir: data/vehicle_detection
  project_name: vehicle_detection

train:
  epochs: 100
  imgsz: 640
  batch: 
  resume: 
  patience: 20
  optimizer: 
  
predict:
  source: 
  conf: 
  iou: 
  imgsz: 640
