model:
  model_dir: models/best.pt
  data_dir: data/test_video
  project_name: vehicle_detection

train:
  epochs: 100
  imgsz: 640
  batch: 
  resume: 
  patience: 20
  optimizer: 
  
predict:
  source: data/vehicle_detection/cctv_footage_frames
  conf: 0.5
  iou: 
  imgsz: 640
  line_width:

track:
  track_id: True
  source: data/test_video/test_video.webm
  save: True
  stream_buffer: True
  vid_stride: 50
  line_width: 1
  verbose: False
  tracker: configs/botsort.yaml

